export const products = [
  { id: 1, name: "Wireless Mouse", price: 19.99, category: "Electronics" },
  { id: 2, name: "Bluetooth Speaker", price: 29.99, category: "Electronics" },
  { id: 3, name: "Notebook", price: 4.99, category: "Stationery" },
  { id: 4, name: "Coffee Mug", price: 7.49, category: "Kitchen" },
  { id: 5, name: "LED Desk Lamp", price: 24.95, category: "Home Decor" },
  { id: 6, name: "Backpack", price: 39.99, category: "Accessories" },
  { id: 7, name: "Yoga Mat", price: 22.99, category: "Fitness" },
  { id: 8, name: "Scented Candles", price: 12.00, category: "Home Decor" },
  { id: 9, name: "Phone Charger", price: 9.99, category: "Electronics" },
  { id: 10, name: "Ballpoint Pen Set", price: 3.49, category: "Stationery" },
  { id: 1, name: "Wireless Mouse", price: 19.99, category: "Electronics" },
  { id: 2, name: "Bluetooth Speaker", price: 29.99, category: "Electronics" },
  { id: 3, name: "Notebook", price: 4.99, category: "Stationery" },
  { id: 4, name: "Coffee Mug", price: 7.49, category: "Kitchen" },
  { id: 5, name: "LED Desk Lamp", price: 24.95, category: "Home Decor" },
  { id: 6, name: "Backpack", price: 39.99, category: "Accessories" },
  { id: 7, name: "Yoga Mat", price: 22.99, category: "Fitness" },
  { id: 8, name: "Scented Candles", price: 12.00, category: "Home Decor" },
  { id: 9, name: "Phone Charger", price: 9.99, category: "Electronics" },
  { id: 10, name: "Ballpoint Pen Set", price: 3.49, category: "Stationery" },
];
